<?php

namespace Database\Seeders\System;

use App\Models\Application;
use App\Models\Module;
use App\Models\SubModule;
use Illuminate\Database\Seeder;

class ApplicationSeeder extends Seeder
{
    public function run(): void
    {
        $generalModule = Module::firstWhere('name', 'general');
        $worldSubModule = SubModule::firstWhere('name', 'world');
        $systemSubModule = SubModule::firstWhere('name', 'system');

        $humanResourcesModule = Module::firstWhere('name', 'human resources');
        $employeeRecordsSubModule = SubModule::firstWhere('name', 'employee records');
        $payrollSubModule = SubModule::firstWhere('name', 'payroll');
        $attendanceTrackingSubModule = SubModule::firstWhere('name', 'attendance tracking');
        $multiOrganizationSubModule = SubModule::firstWhere('name', 'multi organization');

        $financeModule = Module::firstWhere('name', 'finance');
        $generalLedgerSubModule = SubModule::firstWhere('name', 'general ledger');
        $accountsPayableSubModule = SubModule::firstWhere('name', 'accounts payable');
        $accountsReceivableSubModule = SubModule::firstWhere('name', 'accounts receivable');
        $cashSubModule = SubModule::firstWhere('name', 'cash');
        $financeSourcesSubModule = SubModule::firstWhere('name', 'finance sources');
        $costCentersSubModule = SubModule::firstWhere('name', 'cost centers');
        $vatAndTaxSubModule = SubModule::firstWhere('name', 'vat and tax');
        $forecastingSubModule = SubModule::firstWhere('name', 'forecasting');

        $inventoryModule = Module::firstWhere('name', 'inventory');
        $itemsSubModule = SubModule::firstWhere('name', 'items');
        $storesSubModule = SubModule::firstWhere('name', 'stores');

        $projectModule = Module::firstWhere('name', 'project');
        $studySubModule = SubModule::firstWhere('name', 'study');
        $operationsSubModule = SubModule::firstWhere('name', 'operations');

        $contractsModule = Module::firstWhere('name', 'contracts');
        $contractsSubModule = SubModule::firstWhere('name', 'contracts');
        $purchaseOrdersSubModule = SubModule::firstWhere('name', 'purchase orders');
        $paymentTermsSubModule = SubModule::firstWhere('name', 'payment terms');

        Application::insert([
            // General Module Applications
            [
                'name' => 'Countries',
                'code' => $generalModule->code . '-WO-COU',
                'short' => $generalModule->short . '.world.countries',
                'path' => $generalModule->path . '/world/countries',
                'model' => 'App\Models\General\World\Country',
                'view' => 'pages.general.world.countries',
                'controller' => 'App\Livewire\Pages\General\World\Countries',
                'sub_module_id' => $worldSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'States',
                'code' => $generalModule->code . '-WO-STA',
                'short' => $generalModule->short . '.world.states',
                'path' => $generalModule->path . '/world/states',
                'model' => 'App\Models\General\World\State',
                'view' => 'pages.general.world.states',
                'controller' => null,
                'sub_module_id' => $worldSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Cities',
                'code' => $generalModule->code . '-WO-CIT',
                'short' => $generalModule->short . '.world.cities',
                'path' => $generalModule->path . '/world/cities',
                'model' => 'App\Models\General\World\City',
                'view' => 'pages.general.world.cities',
                'controller' => null,
                'sub_module_id' => $worldSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Currencies',
                'code' => $generalModule->code . '-WO-CUR',
                'short' => $generalModule->short . '.world.currencies',
                'path' => $generalModule->path . '/world/currencies',
                'model' => 'App\Models\General\World\Currency',
                'view' => 'pages.general.world.currencies',
                'controller' => null,
                'sub_module_id' => $worldSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Currency Exchange',
                'code' => $generalModule->code . '-WO-CEX',
                'short' => $generalModule->short . '.world.currency-exchange',
                'path' => $generalModule->path . '/world/currency-exchange',
                'model' => 'App\Models\General\World\CurrencyExchange',
                'view' => 'pages.general.world.currency-exchange',
                'controller' => null,
                'sub_module_id' => $worldSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Period',
                'code' => $generalModule->code . '-WO-PER',
                'short' => $generalModule->short . '.world.period',
                'path' => $generalModule->path . '/world/period',
                'model' => 'App\Models\General\World\Period',
                'view' => 'pages.general.world.periods',
                'controller' => null,
                'sub_module_id' => $worldSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Persons',
                'code' => $generalModule->code . '-WO-PRS',
                'short' => $generalModule->short . '.world.persons',
                'path' => $generalModule->path . '/world/persons',
                'model' => 'App\Models\General\World\Person',
                'view' => 'pages.general.world.persons',
                'controller' => null,
                'sub_module_id' => $worldSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Logs',
                'code' => $generalModule->code . '-SY-LOG',
                'short' => $generalModule->short . '.system.logs',
                'path' => $generalModule->path . '/system/logs',
                'model' => 'App\Models\General\System\Log',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $systemSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Settings',
                'code' => $generalModule->code . '-SY-SET',
                'short' => $generalModule->short . '.system.settings',
                'path' => $generalModule->path . '/system/settings',
                'model' => 'App\Models\General\System\Setting',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $systemSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Permissions',
                'code' => $generalModule->code . '-SY-PER',
                'short' => $generalModule->short . '.system.permissions',
                'path' => $generalModule->path . '/system/permissions',
                'model' => 'App\Models\General\System\Permission',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $systemSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Users',
                'code' => $generalModule->code . '-SY-USR',
                'short' => $generalModule->short . '.system.users',
                'path' => $generalModule->path . '/system/users',
                'model' => 'App\Models\General\System\User',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $systemSubModule->id,
                'module_id' => $generalModule->id,
            ],
            [
                'name' => 'Tags',
                'code' => $generalModule->code . '-SY-TAG',
                'short' => $generalModule->short . '.system.tags',
                'path' => $generalModule->path . '/system/tags',
                'model' => 'App\Models\General\System\Tag',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $systemSubModule->id,
                'module_id' => $generalModule->id,
            ],
            // Additional General Module Applications...

            // Human Resource Module Applications
            [
                'name' => 'Employee Categories',
                'code' => $humanResourcesModule->code . '-ER-ECA',
                'short' => $humanResourcesModule->short . '.employee-records.employee-categories',
                'path' => $humanResourcesModule->path . '/employee-records/employee-categories',
                'model' => 'App\Models\HumanResources\EmployeeRecords\EmployeeCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $employeeRecordsSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Employee Profile',
                'code' => $humanResourcesModule->code . '-ER-EPF',
                'short' => $humanResourcesModule->short . '.employee-records.employee-profile',
                'path' => $humanResourcesModule->path . '/employee-records/employee-profile',
                'model' => 'App\Models\HumanResources\EmployeeRecords\EmployeeProfile',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $employeeRecordsSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Employment History',
                'code' => $humanResourcesModule->code . '-ER-EHI',
                'short' => $humanResourcesModule->short . '.employee-records.employment-history',
                'path' => $humanResourcesModule->path . '/employee-records/employment-history',
                'model' => 'App\Models\HumanResources\EmployeeRecords\EmploymentHistory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $employeeRecordsSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Employee Effort Measure',
                'code' => $humanResourcesModule->code . '-ER-EEM',
                'short' => $humanResourcesModule->short . '.employee-records.employee-effort-measure',
                'path' => $humanResourcesModule->path . '/employee-records/employee-effort-measure',
                'model' => 'App\Models\HumanResources\EmployeeRecords\EmployeeEffortMeasure',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $employeeRecordsSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Employee Documents',
                'code' => $humanResourcesModule->code . '-ER-EDO',
                'short' => $humanResourcesModule->short . '.employee-records.employee-documents',
                'path' => $humanResourcesModule->path . '/employee-records/employee-documents',
                'model' => 'App\Models\HumanResources\EmployeeRecords\EmployeeDocument',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $employeeRecordsSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Salary Management',
                'code' => $humanResourcesModule->code . '-PR-SAM',
                'short' => $humanResourcesModule->short . '.payroll.salary-management',
                'path' => $humanResourcesModule->path . '/payroll/salary-management',
                'model' => 'App\Models\HumanResources\Payroll\SalaryManagement',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Payroll Processing',
                'code' => $humanResourcesModule->code . '-PR-PPP',
                'short' => $humanResourcesModule->short . '.payroll.payroll-processing',
                'path' => $humanResourcesModule->path . '/payroll/payroll-processing',
                'model' => 'App\Models\HumanResources\Payroll\PayrollProcessing',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Deductions',
                'code' => $humanResourcesModule->code . '-PR-DED',
                'short' => $humanResourcesModule->short . '.payroll.deductions',
                'path' => $humanResourcesModule->path . '/payroll/deductions',
                'model' => 'App\Models\HumanResources\Payroll\Deduction',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Deduction Types',
                'code' => $humanResourcesModule->code . '-PR-DTY',
                'short' => $humanResourcesModule->short . '.payroll.deduction-types',
                'path' => $humanResourcesModule->path . '/payroll/deduction-types',
                'model' => 'App\Models\HumanResources\Payroll\DeductionType',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Salary Categories',
                'code' => $humanResourcesModule->code . '-PR-SCA',
                'short' => $humanResourcesModule->short . '.payroll.salary-categories',
                'path' => $humanResourcesModule->path . '/payroll/salary-categories',
                'model' => 'App\Models\HumanResources\Payroll\SalaryCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Bonus Management',
                'code' => $humanResourcesModule->code . '-PR-BOM',
                'short' => $humanResourcesModule->short . '.payroll.bonus-management',
                'path' => $humanResourcesModule->path . '/payroll/bonus-management',
                'model' => 'App\Models\HumanResources\Payroll\BonusManagement',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Benefits Types',
                'code' => $humanResourcesModule->code . '-PR-BTY',
                'short' => $humanResourcesModule->short . '.payroll.benefits-types',
                'path' => $humanResourcesModule->path . '/payroll/benefits-types',
                'model' => 'App\Models\HumanResources\Payroll\BenefitType',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Benefits',
                'code' => $humanResourcesModule->code . '-PR-BEN',
                'short' => $humanResourcesModule->short . '.payroll.benefits',
                'path' => $humanResourcesModule->path . '/payroll/benefits',
                'model' => 'App\Models\HumanResources\Payroll\Benefit',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $payrollSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Vacancy Types',
                'code' => $humanResourcesModule->code . '-AT-VTY',
                'short' => $humanResourcesModule->short . '.attendance-tracking.vacancy-types',
                'path' => $humanResourcesModule->path . '/attendance-tracking/vacancy-types',
                'model' => 'App\Models\HumanResources\AttendanceTracking\VacancyType',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $attendanceTrackingSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Vacancy',
                'code' => $humanResourcesModule->code . '-AT-VAC',
                'short' => $humanResourcesModule->short . '.attendance-tracking.vacancy',
                'path' => $humanResourcesModule->path . '/attendance-tracking/vacancy',
                'model' => 'App\Models\HumanResources\AttendanceTracking\Vacancy',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $attendanceTrackingSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Working Hours',
                'code' => $humanResourcesModule->code . '-AT-WHO',
                'short' => $humanResourcesModule->short . '.attendance-tracking.working-hours',
                'path' => $humanResourcesModule->path . '/attendance-tracking/working-hours',
                'model' => 'App\Models\HumanResources\AttendanceTracking\WorkingHour',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $attendanceTrackingSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'In and Out',
                'code' => $humanResourcesModule->code . '-AT-INO',
                'short' => $humanResourcesModule->short . '.attendance-tracking.in-and-out',
                'path' => $humanResourcesModule->path . '/attendance-tracking/in-and-out',
                'model' => 'App\Models\HumanResources\AttendanceTracking\InOut',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $attendanceTrackingSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Companies',
                'code' => $humanResourcesModule->code . '-MO-COM',
                'short' => $humanResourcesModule->short . '.multi-organization.companies',
                'path' => $humanResourcesModule->path . '/multi-organization/companies',
                'model' => 'App\Models\HumanResources\MultiOrganization\Company',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $multiOrganizationSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Branches',
                'code' => $humanResourcesModule->code . '-MO-BRA',
                'short' => $humanResourcesModule->short . '.multi-organization.branches',
                'path' => $humanResourcesModule->path . '/multi-organization/branches',
                'model' => 'App\Models\HumanResources\MultiOrganization\Branch',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $multiOrganizationSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Departments Structures',
                'code' => $humanResourcesModule->code . '-MO-DS',
                'short' => $humanResourcesModule->short . '.multi-organization.departments-structures',
                'path' => $humanResourcesModule->path . '/multi-organization/departments-structures',
                'model' => 'App\Models\HumanResources\MultiOrganization\DepartmentStructure',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $multiOrganizationSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Departments',
                'code' => $humanResourcesModule->code . '-MO-DEP',
                'short' => $humanResourcesModule->short . '.multi-organization.departments',
                'path' => $humanResourcesModule->path . '/multi-organization/departments',
                'model' => 'App\Models\HumanResources\MultiOrganization\Department',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $multiOrganizationSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Positions',
                'code' => $humanResourcesModule->code . '-MO-POS',
                'short' => $humanResourcesModule->short . '.multi-organization.positions',
                'path' => $humanResourcesModule->path . '/multi-organization/positions',
                'model' => 'App\Models\HumanResources\MultiOrganization\Position',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $multiOrganizationSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            [
                'name' => 'Positions Structure',
                'code' => $humanResourcesModule->code . '-MO-PST',
                'short' => $humanResourcesModule->short . '.multi-organization.positions-structure',
                'path' => $humanResourcesModule->path . '/multi-organization/positions-structure',
                'model' => 'App\Models\HumanResources\MultiOrganization\PositionStructure',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $multiOrganizationSubModule->id,
                'module_id' => $humanResourcesModule->id,
            ],
            // Additional Human Resource Module Applications...

            // Finance Module Applications
            [
                'name' => 'Chart of Accounts',
                'code' => $financeModule->code . '-GL-COA',
                'short' => $financeModule->short . '.general-ledger.chart-of-accounts',
                'path' => $financeModule->path . '/general-ledger/chart-of-accounts',
                'model' => 'App\Models\Finance\GeneralLedger\ChartOfAccount',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Groups of Accounts',
                'code' => $financeModule->code . '-GL-GOA',
                'short' => $financeModule->short . '.general-ledger.groups-of-accounts',
                'path' => $financeModule->path . '/general-ledger/groups-of-accounts',
                'model' => 'App\Models\Finance\GeneralLedger\GroupOfAccount',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Accounts',
                'code' => $financeModule->code . '-GL-ACC',
                'short' => $financeModule->short . '.general-ledger.accounts',
                'path' => $financeModule->path . '/general-ledger/accounts',
                'model' => 'App\Models\Finance\GeneralLedger\Account',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Ledgers',
                'code' => $financeModule->code . '-GL-LED',
                'short' => $financeModule->short . '.general-ledger.ledgers',
                'path' => $financeModule->path . '/general-ledger/ledgers',
                'model' => 'App\Models\Finance\GeneralLedger\Ledger',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Journals',
                'code' => $financeModule->code . '-GL-JOU',
                'short' => $financeModule->short . '.general-ledger.journals',
                'path' => $financeModule->path . '/general-ledger/journals',
                'model' => 'App\Models\Finance\GeneralLedger\Journal',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Journal Records',
                'code' => $financeModule->code . '-GL-JOR',
                'short' => $financeModule->short . '.general-ledger.journal-records',
                'path' => $financeModule->path . '/general-ledger/journal-records',
                'model' => 'App\Models\Finance\GeneralLedger\JournalRecord',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Repeated Journals',
                'code' => $financeModule->code . '-GL-RJO',
                'short' => $financeModule->short . '.general-ledger.repeated-journals',
                'path' => $financeModule->path . '/general-ledger/repeated-journals',
                'model' => 'App\Models\Finance\GeneralLedger\RepeatedJournal',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Accounts Budget',
                'code' => $financeModule->code . '-GL-ACB',
                'short' => $financeModule->short . '.general-ledger.accounts-budget',
                'path' => $financeModule->path . '/general-ledger/accounts-budget',
                'model' => 'App\Models\Finance\GeneralLedger\AccountBudget',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $generalLedgerSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Accounts Related',
                'code' => $financeModule->code . '-AP-ACR',
                'short' => $financeModule->short . '.accounts-payable.accounts-related',
                'path' => $financeModule->path . '/accounts-payable/accounts-related',
                'model' => 'App\Models\Finance\AccountsPayable\AccountRelated',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsPayableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Vendors',
                'code' => $financeModule->code . '-AP-VEN',
                'short' => $financeModule->short . '.accounts-payable.vendors',
                'path' => $financeModule->path . '/accounts-payable/vendors',
                'model' => 'App\Models\Finance\AccountsPayable\Vendor',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsPayableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Vendors Categories',
                'code' => $financeModule->code . '-AP-VCA',
                'short' => $financeModule->short . '.accounts-payable.vendors-categories',
                'path' => $financeModule->path . '/accounts-payable/vendors-categories',
                'model' => 'App\Models\Finance\AccountsPayable\VendorCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsPayableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Invoices Types',
                'code' => $financeModule->code . '-AP-INT',
                'short' => $financeModule->short . '.accounts-payable.invoices-types',
                'path' => $financeModule->path . '/accounts-payable/invoices-types',
                'model' => 'App\Models\Finance\AccountsPayable\InvoiceType',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsPayableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Invoices',
                'code' => $financeModule->code . '-AP-INV',
                'short' => $financeModule->short . '.accounts-payable.invoices',
                'path' => $financeModule->path . '/accounts-payable/invoices',
                'model' => 'App\Models\Finance\AccountsPayable\Invoice',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsPayableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Payments',
                'code' => $financeModule->code . '-AP-PAY',
                'short' => $financeModule->short . '.accounts-payable.payments',
                'path' => $financeModule->path . '/accounts-payable/payments',
                'model' => 'App\Models\Finance\AccountsPayable\Payment',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsPayableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Customer Categories',
                'code' => $financeModule->code . '-AR-CCA',
                'short' => $financeModule->short . '.accounts-receivable.customer-categories',
                'path' => $financeModule->path . '/accounts-receivable/customer-categories',
                'model' => 'App\Models\Finance\AccountsReceivable\CustomerCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsReceivableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Customers',
                'code' => $financeModule->code . '-AR-CUS',
                'short' => $financeModule->short . '.accounts-receivable.customers',
                'path' => $financeModule->path . '/accounts-receivable/customers',
                'model' => 'App\Models\Finance\AccountsReceivable\Customer',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsReceivableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Collections',
                'code' => $financeModule->code . '-AR-COL',
                'short' => $financeModule->short . '.accounts-receivable.collections',
                'path' => $financeModule->path . '/accounts-receivable/collections',
                'model' => 'App\Models\Finance\AccountsReceivable\Collection',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $accountsReceivableSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Cash Categories',
                'code' => $financeModule->code . '-CA-CAT',
                'short' => $financeModule->short . '.cash.categories',
                'path' => $financeModule->path . '/cash/categories',
                'model' => 'App\Models\Finance\Cash\CashCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Banks',
                'code' => $financeModule->code . '-CA-BNK',
                'short' => $financeModule->short . '.cash.banks',
                'path' => $financeModule->path . '/cash/banks',
                'model' => 'App\Models\Finance\Cash\Bank',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Safes',
                'code' => $financeModule->code . '-CA-SAF',
                'short' => $financeModule->short . '.cash.safes',
                'path' => $financeModule->path . '/cash/safes',
                'model' => 'App\Models\Finance\Cash\Safe',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Bank Accounts',
                'code' => $financeModule->code . '-CA-BAC',
                'short' => $financeModule->short . '.cash.bank-accounts',
                'path' => $financeModule->path . '/cash/bank-accounts',
                'model' => 'App\Models\Finance\Cash\BankAccount',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Checkbooks',
                'code' => $financeModule->code . '-CA-CHB',
                'short' => $financeModule->short . '.cash.checkbooks',
                'path' => $financeModule->path . '/cash/checkbooks',
                'model' => 'App\Models\Finance\Cash\Checkbook',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Checks',
                'code' => $financeModule->code . '-CA-CHK',
                'short' => $financeModule->short . '.cash.checks',
                'path' => $financeModule->path . '/cash/checks',
                'model' => 'App\Models\Finance\Cash\Check',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Transactions of Cash',
                'code' => $financeModule->code . '-CA-TOC',
                'short' => $financeModule->short . '.cash.transactions-of-cash',
                'path' => $financeModule->path . '/cash/transactions-of-cash',
                'model' => 'App\Models\Finance\Cash\TransactionOfCash',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Cash Budget',
                'code' => $financeModule->code . '-CA-CAB',
                'short' => $financeModule->short . '.cash.cash-budget',
                'path' => $financeModule->path . '/cash/cash-budget',
                'model' => 'App\Models\Finance\Cash\CashBudget',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $cashSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Finance Categories',
                'code' => $financeModule->code . '-FS-FCA',
                'short' => $financeModule->short . '.finance-sources.finance-categories',
                'path' => $financeModule->path . '/finance-sources/finance-categories',
                'model' => 'App\Models\Finance\FinanceSources\FinanceCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $financeSourcesSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Finance Lines',
                'code' => $financeModule->code . '-FS-FLI',
                'short' => $financeModule->short . '.finance-sources.finance-lines',
                'path' => $financeModule->path . '/finance-sources/finance-lines',
                'model' => 'App\Models\Finance\FinanceSources\FinanceLine',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $financeSourcesSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Finance Transactions',
                'code' => $financeModule->code . '-FS-FTR',
                'short' => $financeModule->short . '.finance-sources.finance-transactions',
                'path' => $financeModule->path . '/finance-sources/finance-transactions',
                'model' => 'App\Models\Finance\FinanceSources\FinanceTransaction',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $financeSourcesSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Cost Center Categories',
                'code' => $financeModule->code . '-CC-CCC',
                'short' => $financeModule->short . '.cost-centers.cost-center-categories',
                'path' => $financeModule->path . '/cost-centers/cost-center-categories',
                'model' => 'App\Models\Finance\CostCenters\CostCenterCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $costCentersSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Cost Centers',
                'code' => $financeModule->code . '-CC-CEN',
                'short' => $financeModule->short . '.cost-centers.cost-centers',
                'path' => $financeModule->path . '/cost-centers/cost-centers',
                'model' => 'App\Models\Finance\CostCenters\CostCenter',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $costCentersSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Cost Center Transactions',
                'code' => $financeModule->code . '-CC-CCT',
                'short' => $financeModule->short . '.cost-centers.cost-center-transactions',
                'path' => $financeModule->path . '/cost-centers/cost-center-transactions',
                'model' => 'App\Models\Finance\CostCenters\CostCenterTransaction',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $costCentersSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Cost Center Budget',
                'code' => $financeModule->code . '-CC-CAB',
                'short' => $financeModule->short . '.cost-centers.cost-center-budget',
                'path' => $financeModule->path . '/cost-centers/cost-center-budget',
                'model' => 'App\Models\Finance\CostCenters\CostCenterBudget',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $costCentersSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'VAT Categories',
                'code' => $financeModule->code . '-VT-VAC',
                'short' => $financeModule->short . '.vat-and-tax.vat-categories',
                'path' => $financeModule->path . '/vat-and-tax/vat-categories',
                'model' => 'App\Models\Finance\VatAndTax\VATCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $vatAndTaxSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'VAT',
                'code' => $financeModule->code . '-VT-VAT',
                'short' => $financeModule->short . '.vat-and-tax.vat',
                'path' => $financeModule->path . '/vat-and-tax/vat',
                'model' => 'App\Models\Finance\VatAndTax\VAT',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $vatAndTaxSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'VAT Transactions',
                'code' => $financeModule->code . '-VT-VTT',
                'short' => $financeModule->short . '.vat-and-tax.vat-transactions',
                'path' => $financeModule->path . '/vat-and-tax/vat-transactions',
                'model' => 'App\Models\Finance\VatAndTax\VATTransaction',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $vatAndTaxSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Forecasted Category',
                'code' => $financeModule->code . '-FO-FCT',
                'short' => $financeModule->short . '.forecasting.forecasted-category',
                'path' => $financeModule->path . '/forecasting/forecasted-category',
                'model' => 'App\Models\Finance\Forecasting\ForecastedCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $forecastingSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Forecasted Transactions',
                'code' => $financeModule->code . '-FO-FTT',
                'short' => $financeModule->short . '.forecasting.forecasted-transactions',
                'path' => $financeModule->path . '/forecasting/forecasted-transactions',
                'model' => 'App\Models\Finance\Forecasting\ForecastedTransaction',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $forecastingSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Forecasted Ledgers',
                'code' => $financeModule->code . '-FO-FLG',
                'short' => $financeModule->short . '.forecasting.forecasted-ledgers',
                'path' => $financeModule->path . '/forecasting/forecasted-ledgers',
                'model' => 'App\Models\Finance\Forecasting\ForecastedLedger',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $forecastingSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Forecasted In',
                'code' => $financeModule->code . '-FO-FIN',
                'short' => $financeModule->short . '.forecasting.forecasted-in',
                'path' => $financeModule->path . '/forecasting/forecasted-in',
                'model' => 'App\Models\Finance\Forecasting\ForecastedIn',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $forecastingSubModule->id,
                'module_id' => $financeModule->id,
            ],
            [
                'name' => 'Forecasted Out',
                'code' => $financeModule->code . '-FO-FOT',
                'short' => $financeModule->short . '.forecasting.forecasted-out',
                'path' => $financeModule->path . '/forecasting/forecasted-out',
                'model' => 'App\Models\Finance\Forecasting\ForecastedOut',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $forecastingSubModule->id,
                'module_id' => $financeModule->id,
            ],
            // Additional Finance Module Applications...

            // Inventory Module Applications
            [
                'name' => 'Items Categories',
                'code' => $inventoryModule->code . '-IT-ITC',
                'short' => $inventoryModule->short . '.items.items-categories',
                'path' => $inventoryModule->path . '/items/items-categories',
                'model' => 'App\Models\Inventory\Items\ItemCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $itemsSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            [
                'name' => 'Items Groups',
                'code' => $inventoryModule->code . '-IT-ITG',
                'short' => $inventoryModule->short . '.items.items-groups',
                'path' => $inventoryModule->path . '/items/items-groups',
                'model' => 'App\Models\Inventory\Items\ItemGroup',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $itemsSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            [
                'name' => 'Items',
                'code' => $inventoryModule->code . '-IT-ITM',
                'short' => $inventoryModule->short . '.items.items',
                'path' => $inventoryModule->path . '/items/items',
                'model' => 'App\Models\Inventory\Items\Item',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $itemsSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            [
                'name' => 'Items Pricing',
                'code' => $inventoryModule->code . '-IT-ITP',
                'short' => $inventoryModule->short . '.items.items-pricing',
                'path' => $inventoryModule->path . '/items/items-pricing',
                'model' => 'App\Models\Inventory\Items\ItemPricing',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $itemsSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            [
                'name' => 'Stores Categories',
                'code' => $inventoryModule->code . '-ST-STC',
                'short' => $inventoryModule->short . '.stores.stores-categories',
                'path' => $inventoryModule->path . '/stores/stores-categories',
                'model' => 'App\Models\Inventory\Stores\StoreCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $storesSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            [
                'name' => 'Stores',
                'code' => $inventoryModule->code . '-ST-STO',
                'short' => $inventoryModule->short . '.stores.stores',
                'path' => $inventoryModule->path . '/stores/stores',
                'model' => 'App\Models\Inventory\Stores\Store',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $storesSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            [
                'name' => 'In Transactions',
                'code' => $inventoryModule->code . '-ST-INT',
                'short' => $inventoryModule->short . '.stores.in-transactions',
                'path' => $inventoryModule->path . '/stores/in-transactions',
                'model' => 'App\Models\Inventory\Stores\InTransaction',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $storesSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            [
                'name' => 'Out Transactions',
                'code' => $inventoryModule->code . '-ST-OUT',
                'short' => $inventoryModule->short . '.stores.out-transactions',
                'path' => $inventoryModule->path . '/stores/out-transactions',
                'model' => 'App\Models\Inventory\Stores\OutTransaction',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $storesSubModule->id,
                'module_id' => $inventoryModule->id,
            ],
            // Additional Inventory Module Applications...

            // Project Module Applications
            [
                'name' => 'Tender Categories',
                'code' => $projectModule->code . '-ST-TDC',
                'short' => $projectModule->short . '.study.tender-categories',
                'path' => $projectModule->path . '/study/tender-categories',
                'model' => 'App\Models\Project\Study\TenderCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tender',
                'code' => $projectModule->code . '-ST-TND',
                'short' => $projectModule->short . '.study.tender',
                'path' => $projectModule->path . '/study/tender',
                'model' => 'App\Models\Project\Study\Tender',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tender Lines',
                'code' => $projectModule->code . '-ST-TDL',
                'short' => $projectModule->short . '.study.tender-lines',
                'path' => $projectModule->path . '/study/tender-lines',
                'model' => 'App\Models\Project\Study\TenderLine',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tender Line Cost',
                'code' => $projectModule->code . '-ST-TLC',
                'short' => $projectModule->short . '.study.tender-line-cost',
                'path' => $projectModule->path . '/study/tender-line-cost',
                'model' => 'App\Models\Project\Study\TenderLineCost',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tender Total Cost',
                'code' => $projectModule->code . '-ST-TTC',
                'short' => $projectModule->short . '.study.tender-total-cost',
                'path' => $projectModule->path . '/study/tender-total-cost',
                'model' => 'App\Models\Project\Study\TenderTotalCost',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tender Pricing',
                'code' => $projectModule->code . '-ST-TPR',
                'short' => $projectModule->short . '.study.tender-pricing',
                'path' => $projectModule->path . '/study/tender-pricing',
                'model' => 'App\Models\Project\Study\TenderPricing',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tender Line Pricing',
                'code' => $projectModule->code . '-ST-TLP',
                'short' => $projectModule->short . '.study.tender-line-pricing',
                'path' => $projectModule->path . '/study/tender-line-pricing',
                'model' => 'App\Models\Project\Study\TenderLinePricing',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Budgets for Tender',
                'code' => $projectModule->code . '-ST-BFT',
                'short' => $projectModule->short . '.study.budgets-for-tender',
                'path' => $projectModule->path . '/study/budgets-for-tender',
                'model' => 'App\Models\Project\Study\BudgetForTender',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $studySubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tasks Categories',
                'code' => $projectModule->code . '-OP-TCA',
                'short' => $projectModule->short . '.operations.tasks-categories',
                'path' => $projectModule->path . '/operations/tasks-categories',
                'model' => 'App\Models\Project\Operations\TaskCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $operationsSubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Tasks',
                'code' => $projectModule->code . '-OP-TSK',
                'short' => $projectModule->short . '.operations.tasks',
                'path' => $projectModule->path . '/operations/tasks',
                'model' => 'App\Models\Project\Operations\Task',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $operationsSubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Operation Measure for Projects',
                'code' => $projectModule->code . '-OP-OMP',
                'short' => $projectModule->short . '.operations.operation-measure-for-projects',
                'path' => $projectModule->path . '/operations/operation-measure-for-projects',
                'model' => 'App\Models\Project\Operations\OperationMeasureForProject',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $operationsSubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Operation Plans',
                'code' => $projectModule->code . '-OP-OPL',
                'short' => $projectModule->short . '.operations.operation-plans',
                'path' => $projectModule->path . '/operations/operation-plans',
                'model' => 'App\Models\Project\Operations\OperationPlan',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $operationsSubModule->id,
                'module_id' => $projectModule->id,
            ],
            [
                'name' => 'Operation Plan Line',
                'code' => $projectModule->code . '-OP-OLL',
                'short' => $projectModule->short . '.operations.operation-plan-line',
                'path' => $projectModule->path . '/operations/operation-plan-line',
                'model' => 'App\Models\Project\Operations\OperationPlanLine',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $operationsSubModule->id,
                'module_id' => $projectModule->id,
            ],
            // Additional Project Module Applications...

            // Contracts Module Applications
            [
                'name' => 'Contract Categories',
                'code' => $contractsModule->code . '-CT-CCA',
                'short' => $contractsModule->short . '.contracts.contract-categories',
                'path' => $contractsModule->path . '/contracts/contract-categories',
                'model' => 'App\Models\Contracts\Contracts\ContractCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $contractsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Contracts',
                'code' => $contractsModule->code . '-CT-CON',
                'short' => $contractsModule->short . '.contracts.contracts',
                'path' => $contractsModule->path . '/contracts/contracts',
                'model' => 'App\Models\Contracts\Contracts\Contract',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $contractsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Contract Lines',
                'code' => $contractsModule->code . '-CT-CLN',
                'short' => $contractsModule->short . '.contracts.contract-lines',
                'path' => $contractsModule->path . '/contracts/contract-lines',
                'model' => 'App\Models\Contracts\Contracts\ContractLine',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $contractsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Contract Budgets',
                'code' => $contractsModule->code . '-CT-CBG',
                'short' => $contractsModule->short . '.contracts.contract-budgets',
                'path' => $contractsModule->path . '/contracts/contract-budgets',
                'model' => 'App\Models\Contracts\Contracts\ContractBudget',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $contractsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Contract Pricing',
                'code' => $contractsModule->code . '-CT-CPR',
                'short' => $contractsModule->short . '.contracts.contract-pricing',
                'path' => $contractsModule->path . '/contracts/contract-pricing',
                'model' => 'App\Models\Contracts\Contracts\ContractPricing',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $contractsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Contract Cost',
                'code' => $contractsModule->code . '-CT-CCO',
                'short' => $contractsModule->short . '.contracts.contract-cost',
                'path' => $contractsModule->path . '/contracts/contract-cost',
                'model' => 'App\Models\Contracts\Contracts\ContractCost',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $contractsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Purchase Order Categories',
                'code' => $contractsModule->code . '-PO-POC',
                'short' => $contractsModule->short . '.purchase-orders.purchase-order-categories',
                'path' => $contractsModule->path . '/purchase-orders/purchase-order-categories',
                'model' => 'App\Models\Contracts\PurchaseOrders\PurchaseOrderCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $purchaseOrdersSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Purchase Orders',
                'code' => $contractsModule->code . '-PO-ORD',
                'short' => $contractsModule->short . '.purchase-orders.purchase-orders',
                'path' => $contractsModule->path . '/purchase-orders/purchase-orders',
                'model' => 'App\Models\Contracts\PurchaseOrders\PurchaseOrder',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $purchaseOrdersSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Purchase Order Lines',
                'code' => $contractsModule->code . '-PO-POL',
                'short' => $contractsModule->short . '.purchase-orders.purchase-order-lines',
                'path' => $contractsModule->path . '/purchase-orders/purchase-order-lines',
                'model' => 'App\Models\Contracts\PurchaseOrders\PurchaseOrderLine',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $purchaseOrdersSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Purchase Order Cost',
                'code' => $contractsModule->code . '-PO-POCO',
                'short' => $contractsModule->short . '.purchase-orders.purchase-order-cost',
                'path' => $contractsModule->path . '/purchase-orders/purchase-order-cost',
                'model' => 'App\Models\Contracts\PurchaseOrders\PurchaseOrderCost',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $purchaseOrdersSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Purchase Order Pricing',
                'code' => $contractsModule->code . '-PO-PRC',
                'short' => $contractsModule->short . '.purchase-orders.purchase-order-pricing',
                'path' => $contractsModule->path . '/purchase-orders/purchase-order-pricing',
                'model' => 'App\Models\Contracts\PurchaseOrders\PurchaseOrderPricing',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $purchaseOrdersSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Purchase Order Budget',
                'code' => $contractsModule->code . '-PO-PBG',
                'short' => $contractsModule->short . '.purchase-orders.purchase-order-budget',
                'path' => $contractsModule->path . '/purchase-orders/purchase-order-budget',
                'model' => 'App\Models\Contracts\PurchaseOrders\PurchaseOrderBudget',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $purchaseOrdersSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Payment Term Category',
                'code' => $contractsModule->code . '-PT-PTC',
                'short' => $contractsModule->short . '.payment-terms.payment-term-category',
                'path' => $contractsModule->path . '/payment-terms/payment-term-category',
                'model' => 'App\Models\Contracts\PaymentTerms\PaymentTermCategory',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $paymentTermsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Payment Term',
                'code' => $contractsModule->code . '-PT-PTM',
                'short' => $contractsModule->short . '.payment-terms.payment-term',
                'path' => $contractsModule->path . '/payment-terms/payment-term',
                'model' => 'App\Models\Contracts\PaymentTerms\PaymentTerm',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $paymentTermsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            [
                'name' => 'Payment Term Lines',
                'code' => $contractsModule->code . '-PT-PTL',
                'short' => $contractsModule->short . '.payment-terms.payment-term-lines',
                'path' => $contractsModule->path . '/payment-terms/payment-term-lines',
                'model' => 'App\Models\Contracts\PaymentTerms\PaymentTermLine',
                'view' => null,
                'controller' => null,
                'sub_module_id' => $paymentTermsSubModule->id,
                'module_id' => $contractsModule->id,
            ],
            // Additional Contracts Module Applications...
        ]);
    }
}
